export const ERROR_CODES = {
  // Authentication
  AUTH_INVALID_CREDENTIALS: 'AUTH_001',
  AUTH_UNAUTHORIZED: 'AUTH_002',
  AUTH_TOKEN_EXPIRED: 'AUTH_003',
  AUTH_TOKEN_INVALID: 'AUTH_004',

  // Validation
  VALIDATION_FAILED: 'VAL_001',
  VALIDATION_MISSING_FIELD: 'VAL_002',
  VALIDATION_INVALID_FORMAT: 'VAL_003',
  VALIDATION_IMAGE_INVALID: 'VAL_004',

  // Vision API
  VISION_API_ERROR: 'VISION_001',
  VISION_API_TIMEOUT: 'VISION_002',
  VISION_NO_TEXT_DETECTED: 'VISION_003',
  VISION_LOW_CONFIDENCE: 'VISION_004',

  // Database
  DB_ERROR: 'DB_001',
  DB_CONNECTION_FAILED: 'DB_002',
  DB_RECORD_NOT_FOUND: 'DB_003',

  // Batch Processing
  BATCH_INVALID_SIZE: 'BATCH_001',
  BATCH_PROCESSING_ERROR: 'BATCH_002',
  BATCH_TIMEOUT: 'BATCH_003',

  // File Operations
  FILE_UPLOAD_FAILED: 'FILE_001',
  FILE_TOO_LARGE: 'FILE_002',
  FILE_INVALID_TYPE: 'FILE_003',

  // General
  INTERNAL_ERROR: 'ERR_001',
  NOT_FOUND: 'ERR_002',
  BAD_REQUEST: 'ERR_003',
  FORBIDDEN: 'ERR_004',
  CONFLICT: 'ERR_005',
  RATE_LIMITED: 'ERR_006',
} as const;
